// AUTO-GENERATED BY scripts/generate-types.mjs. DO NOT EDIT BY HAND.
// Run `npm run generate:types` to regenerate.
export interface Films {
    title:         string;
    episode_id:    number;
    opening_crawl: string;
    director:      string;
    producer:      string;
    release_date:  string;
    characters:    string[];
    planets:       string[];
    starships:     string[];
    vehicles:      string[];
    species:       string[];
    created:       string;
    edited:        string;
    url:           string;
}
