// AUTO-GENERATED BY scripts/generate-types.mjs. DO NOT EDIT BY HAND.
// Run `npm run generate:types` to regenerate.

export type { People } from "./people";
export type { Planets } from "./planets";
export type { Films } from "./films";
export type { Species } from "./species";
export type { Vehicles } from "./vehicles";
export type { Starships } from "./starships";
export type { SwapiRoot } from "./root";

import type { People } from "./people";
import type { Planets } from "./planets";
import type { Films } from "./films";
import type { Species } from "./species";
import type { Vehicles } from "./vehicles";
import type { Starships } from "./starships";
import type { SwapiRoot } from "./root";

/** Union of all SWAPI resource item types (single entity from the API). */
export type SwapiResourceItem =
  | People
  | Planets
  | Films
  | Species
  | Vehicles
  | Starships;

/** Resource keys that have both a list endpoint and a detail endpoint. */
export type SwapiResourceKey = keyof SwapiRoot;
