// AUTO-GENERATED BY scripts/generate-types.mjs. DO NOT EDIT BY HAND.
// Run `npm run generate:types` to regenerate.
export interface SwapiRoot {
    people:    string;
    planets:   string;
    films:     string;
    species:   string;
    vehicles:  string;
    starships: string;
}
